[package]
name = "clew-widgets"
version = "0.0.1"
edition = "2024"

[dependencies]
log = { workspace = true }
clew = { path = "../clew" }
clew-derive = { path = "../clew-derive" }
profiling = { workspace = true }
