[package]
name = "tech_paws_ui_tiny_skia"
version = "0.1.0"
edition = "2024"

[dependencies]
tiny-skia = "0.11"
softbuffer = "0.4"
tech_paws_ui = { path = "../tech_paws_ui" }
raw-window-handle = { workspace = true }
