[package]
name = "tech-paws-ui-tiny-skia"
version = "0.1.0"
edition = "2024"

[dependencies]
tiny-skia = "0.11"
softbuffer = "0.4"
tech-paws-ui = { path = "../tech-paws-ui" }
raw-window-handle = { workspace = true }
cosmic-text = { workspace = true }
